#!/bin/bash

PASS=`cat /root/.mysql_secret | sed -e "s/.*(local time): //"`
expect -c "
  spawn mysql -p
    expect \"Enter Password:\"
    send \"${PASS}\n\"
    expect \"mysql>\"
    send \"SET PASSWORD FOR root@localhost=PASSWORD('');\n\"
    expect \"mysql>\"
    send \"exit\n\"
  interact
"
# rm -f .mysql_secret

exit 0
